'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="WorkRequest")>  _
Partial Public Class DBHRMSDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.RISTMACHINE.My.MySettings.Default.WorkRequestConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property vewHrmsOPIDs() As System.Data.Linq.Table(Of vewHrmsOPID)
		Get
			Return Me.GetTable(Of vewHrmsOPID)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vewHrmsOPID")>  _
Partial Public Class vewHrmsOPID
	
	Private _CODEMPID As String
	
	Private _NAMEMPT As String
	
	Private _NAMEMPE As String
	
	Private _COMPANY As String
	
	Private _DIVISION As String
	
	Private _SECTION As String
	
	Private _DEPARTMENT As String
	
	Private _DEPARTMENT2 As String
	
	Private _DEPARTMENT3 As String
	
	Private _ORGANIZATIONNAME As String
	
	Private _POSITION As String
	
	Private _EMPLEVEL As System.Nullable(Of Double)
	
	Private _EMAIL As String
	
	Private _DTEBIRTH As System.Nullable(Of Date)
	
	Private _AGE As String
	
	Private _PASSPORT As String
	
	Private _NATIONALITY As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CODEMPID", DbType:="NVarChar(8) NOT NULL", CanBeNull:=false)>  _
	Public Property CODEMPID() As String
		Get
			Return Me._CODEMPID
		End Get
		Set
			If (String.Equals(Me._CODEMPID, value) = false) Then
				Me._CODEMPID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAMEMPT", DbType:="NVarChar(60)")>  _
	Public Property NAMEMPT() As String
		Get
			Return Me._NAMEMPT
		End Get
		Set
			If (String.Equals(Me._NAMEMPT, value) = false) Then
				Me._NAMEMPT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAMEMPE", DbType:="NVarChar(60)")>  _
	Public Property NAMEMPE() As String
		Get
			Return Me._NAMEMPE
		End Get
		Set
			If (String.Equals(Me._NAMEMPE, value) = false) Then
				Me._NAMEMPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(4000)")>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me._COMPANY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DIVISION", DbType:="NVarChar(4000)")>  _
	Public Property DIVISION() As String
		Get
			Return Me._DIVISION
		End Get
		Set
			If (String.Equals(Me._DIVISION, value) = false) Then
				Me._DIVISION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SECTION", DbType:="NVarChar(4000)")>  _
	Public Property SECTION() As String
		Get
			Return Me._SECTION
		End Get
		Set
			If (String.Equals(Me._SECTION, value) = false) Then
				Me._SECTION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTMENT", DbType:="NVarChar(4000)")>  _
	Public Property DEPARTMENT() As String
		Get
			Return Me._DEPARTMENT
		End Get
		Set
			If (String.Equals(Me._DEPARTMENT, value) = false) Then
				Me._DEPARTMENT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTMENT2", DbType:="NVarChar(4000)")>  _
	Public Property DEPARTMENT2() As String
		Get
			Return Me._DEPARTMENT2
		End Get
		Set
			If (String.Equals(Me._DEPARTMENT2, value) = false) Then
				Me._DEPARTMENT2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTMENT3", DbType:="NVarChar(4000)")>  _
	Public Property DEPARTMENT3() As String
		Get
			Return Me._DEPARTMENT3
		End Get
		Set
			If (String.Equals(Me._DEPARTMENT3, value) = false) Then
				Me._DEPARTMENT3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORGANIZATIONNAME", DbType:="NVarChar(4000)")>  _
	Public Property ORGANIZATIONNAME() As String
		Get
			Return Me._ORGANIZATIONNAME
		End Get
		Set
			If (String.Equals(Me._ORGANIZATIONNAME, value) = false) Then
				Me._ORGANIZATIONNAME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_POSITION", DbType:="NVarChar(4000)")>  _
	Public Property POSITION() As String
		Get
			Return Me._POSITION
		End Get
		Set
			If (String.Equals(Me._POSITION, value) = false) Then
				Me._POSITION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMPLEVEL", DbType:="Float")>  _
	Public Property EMPLEVEL() As System.Nullable(Of Double)
		Get
			Return Me._EMPLEVEL
		End Get
		Set
			If (Me._EMPLEVEL.Equals(value) = false) Then
				Me._EMPLEVEL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="NVarChar(50)")>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me._EMAIL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTEBIRTH", DbType:="DateTime2")>  _
	Public Property DTEBIRTH() As System.Nullable(Of Date)
		Get
			Return Me._DTEBIRTH
		End Get
		Set
			If (Me._DTEBIRTH.Equals(value) = false) Then
				Me._DTEBIRTH = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AGE", DbType:="NVarChar(4000)")>  _
	Public Property AGE() As String
		Get
			Return Me._AGE
		End Get
		Set
			If (String.Equals(Me._AGE, value) = false) Then
				Me._AGE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PASSPORT", DbType:="NVarChar(20)")>  _
	Public Property PASSPORT() As String
		Get
			Return Me._PASSPORT
		End Get
		Set
			If (String.Equals(Me._PASSPORT, value) = false) Then
				Me._PASSPORT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NATIONALITY", DbType:="NVarChar(4000)")>  _
	Public Property NATIONALITY() As String
		Get
			Return Me._NATIONALITY
		End Get
		Set
			If (String.Equals(Me._NATIONALITY, value) = false) Then
				Me._NATIONALITY = value
			End If
		End Set
	End Property
End Class
