'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminSetFlow
    
    '''<summary>
    '''gvflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvflow As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbmodalhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmodalhead As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtopnorequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnorequest As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtopnosectmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnosectmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemailsectmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemailsectmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtopnodeptmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnodeptmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemaildeptmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemaildeptmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtopnodivmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnodivmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemaildivmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemaildivmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbmsgmodalsect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodalsect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbmsgmodaldept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodaldept As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbmsgmodaldiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodaldiv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnksave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksave As Global.System.Web.UI.WebControls.LinkButton
End Class
