'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminSetFlowSafety
    
    '''<summary>
    '''gvflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvflow As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbmodalhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmodalhead As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtopnosubcom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnosubcom As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemailsubcom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemailsubcom As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtopnosfofficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnosfofficer As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemailsfofficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemailsfofficer As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtopnosfmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtopnosfmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemailsfmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemailsfmgr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbmsgmodalsubcom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodalsubcom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbmsgmodalsfofficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodalsfofficer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbmsgmodalsfmgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsgmodalsfmgr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnksave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksave As Global.System.Web.UI.WebControls.LinkButton
End Class
