'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EquipmentCheck
    
    '''<summary>
    '''lbmcno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmcno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_mcname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_mcname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_mcno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_mcno As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbmcfront control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmcfront As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbmcback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmcback As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tbemersdt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk11 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk12 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk13 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk14 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk15 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk16 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk17 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbemersdt8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersdt8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbemersno8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemersno8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk18 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk21 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk22 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk23 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk24 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk25 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk26 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk27 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbareas8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareas8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbareasno8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbareasno8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk28 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk31 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk32 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk33 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk34 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk35 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk36 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk37 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tbsafecover8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecover8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbsafecoverno8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsafecoverno8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk38 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk41 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk42 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk43 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk44 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk45 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk46 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk47 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tblimitsw8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitsw8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tblimitswno8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblimitswno8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chk48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk48 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''tb_organize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_organize As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_building As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_floor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_floor As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tb_process control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_process As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbmsglayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmsglayout As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkdownload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdownload3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnksave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksave As Global.System.Web.UI.WebControls.LinkButton
End Class
