'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Securitychecktool
    
    '''<summary>
    '''lbmcno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmcno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''select_imp1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_11 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_11 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str3_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str3_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicex11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicex11 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbx11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbx11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespx11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespx11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtx11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtx11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceb12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceb12 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbb12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbb12 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespb12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespb12 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtb12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtb12 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicec13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicec13 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbc13 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespc13 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtc13 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiced14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiced14 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbd14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbd14 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespd14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespd14 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtd14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtd14 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicee15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicee15 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbe15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbe15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespe15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespe15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdte15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdte15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicef16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicef16 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbf16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbf16 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespf16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespf16 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtf16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtf16 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceg17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceg17 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbg17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbg17 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespg17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespg17 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtg17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtg17 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceh18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceh18 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbh18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbh18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbresph18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbresph18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdth18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdth18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicei19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicei19 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbi19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbi19 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespi19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespi19 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdti19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdti19 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicej20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicej20 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbj20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbj20 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespj20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespj20 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtj20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtj20 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicek21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicek21 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbk21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbk21 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespk21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespk21 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtk21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtk21 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicel22 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbl22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbl22 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespl22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespl22 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtl22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtl22 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicem23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicem23 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbm23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbm23 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespm23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespm23 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtm23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtm23 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicen24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicen24 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbn24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbn24 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespn24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespn24 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtn24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtn24 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceo25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceo25 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbo25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbo25 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespo25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespo25 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdto25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdto25 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicep26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicep26 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbp26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbp26 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespp26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespp26 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtp26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtp26 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceq27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceq27 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbq27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbq27 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespq27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespq27 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtq27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtq27 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicer28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicer28 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbr28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbr28 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespr28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespr28 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtr28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtr28 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choices29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choices29 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbs29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbs29 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbresps29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbresps29 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdts29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdts29 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicet30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicet30 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbt30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbt30 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespt30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespt30 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtt30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtt30 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceu31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceu31 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbu31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbu31 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespu31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespu31 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtu31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtu31 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicev32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicev32 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbv32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbv32 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespv32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespv32 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtv32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtv32 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicew33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicew33 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbw33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbw33 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespw33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespw33 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtw33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtw33 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicex34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicex34 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbx34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbx34 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespx34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespx34 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtx34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtx34 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicey35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicey35 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpby35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpby35 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespy35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespy35 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdty35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdty35 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicez36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicez36 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbz36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbz36 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespz36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespz36 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtz36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtz36 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choiceza37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choiceza37 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbza37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbza37 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespza37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespza37 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtza37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtza37 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicezx38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicezx38 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbzx38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbzx38 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespzx38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespzx38 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtzx38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtzx38 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicezc39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicezc39 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbzc39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbzc39 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespzc39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespzc39 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtzc39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtzc39 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicezv40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicezv40 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbzv40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbzv40 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespzv40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespzv40 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtzv40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtzv40 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''choicezs41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choicezs41 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tbpbzs41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpbzs41 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbrespzs41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbrespzs41 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbdtzs41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdtzs41 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lnksave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksave As Global.System.Web.UI.WebControls.LinkButton
End Class
