'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Securitychecktool
    
    '''<summary>
    '''lbmcno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmcno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''select_imp1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp1_11 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp1_11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str1_11 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str1_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str1_11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp12_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp12_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str12_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str12_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp2_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp2_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str2_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str2_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_4 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_5 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_6 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_7 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_7 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_8 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_9 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp31_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp31_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str31_10 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str31_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str31_10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp32_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp32_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str32_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str32_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str32_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp33_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp33_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str33_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str33_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str33_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp34_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp34_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp34_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp34_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str34_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str34_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str34_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str34_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp34_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp34_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp34_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp34_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str34_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str34_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str34_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str34_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp34_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp34_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp34_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp34_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str34_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str34_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str34_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str34_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_E As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_E As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_F As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_F As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp4_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp4_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp4_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp4_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str4_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str4_G As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str4_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str4_G As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp51_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp51_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp51_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp51_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str51_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str51_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str51_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str51_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp51_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp51_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp51_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp51_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str51_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str51_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str51_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str51_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp52_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp52_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp52_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp52_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str52_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str52_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str52_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str52_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp52_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp52_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp52_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp52_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str52_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str52_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str52_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str52_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp52_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp52_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp52_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp52_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str52_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str52_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str52_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str52_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp53_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp53_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp53_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp53_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str53_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str53_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str53_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str53_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp53_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp53_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp53_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp53_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str53_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str53_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str53_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str53_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp53_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp53_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp53_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp53_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str53_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str53_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str53_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str53_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp53_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp53_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp53_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp53_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str53_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str53_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str53_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str53_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp54_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp54_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp54_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp54_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str54_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str54_A As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str54_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str54_A As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp54_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp54_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp54_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp54_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str54_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str54_B As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str54_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str54_B As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp54_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp54_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp54_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp54_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str54_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str54_C As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str54_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str54_C As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_imp54_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_imp54_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_imp54_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_imp54_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''select_str54_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_str54_D As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tb_str54_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_str54_D As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lnksave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gvDetailsMcno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetailsMcno As Global.System.Web.UI.WebControls.GridView
End Class
