USE [DBRISTMC]
GO

/****** Object:  Table [dbo].[TB_FLOW_REQUEST]    Script Date: 09/11/2018 8:12:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_FLOW_REQUEST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REQUEST_OP] [varchar](10) NOT NULL,
	[SECT_MGR_OP] [varchar](10) NULL,
	[SECT_MGR_EMAIL] [varchar](30) NULL,
	[SECT_MGR_STAMP] [varchar](20) NULL,
	[DEPT_MGR_OP] [varchar](10) NULL,
	[DEPT_MGR_EMAIL] [varchar](30) NULL,
	[DEPT_MGR_STAMP] [varchar](20) NULL,
	[DIV_MGR_OP] [varchar](10) NULL,
	[DIV_MGR_EMAIL] [varchar](30) NULL,
	[DIV_MGR_STAMP] [varchar](20) NULL,
	[RATING] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[ADMIN_OP] [varchar](10) NULL,
 CONSTRAINT [PK_TB_FLOW_REQUEST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


